# Generated by Django 2.0 on 2020-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apiresponse',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='返回结果'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apistep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='测试步骤'),
        ),
    ]
